name: Cleanup Feature Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  cleanup:
    name: Remove Feature Deployment
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Delete feature deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DO_SPACES_BUCKET: ${{ secrets.DO_SPACES_BUCKET }}
          DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_ACTIONS: 'true'
        run: node cleanup-feature.js

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const featureName = branch.replace(/^feature\//, '').replace(/[^a-zA-Z0-9-_/]/g, '-').toLowerCase();

            const comment = `## 🧹 Feature Deployment Cleaned Up

            The deployment for \`${branch}\` has been removed from Digital Ocean Spaces.

            **Removed path:** \`cxone-expert-enhancements/feature/${featureName}/\`

            This cleanup happened automatically because the PR was merged to \`${context.payload.pull_request.base.ref}\`.
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
