name: Deploy Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Develop Branch
    uses: ./.github/workflows/deploy-reusable.yml
    secrets: inherit
    with:
      branch_name: develop
      deployment_path: develop
